### ISSUE TITLE
Optionsnya bermasalah!

### ISSUE THREAD

**Issue by PixieID** [4relial/JadiAnime#1]
Uploadnya selalu gagal sampe udh nyoba 17x an.
Klo gamake options , QQ ngeblock IP/Region

**Comment by 4relial** [comment]
> Uploadnya selalu gagal sampe udh nyoba 17x an. Klo gamake options , QQ ngeblock IP/Region

Pake proxy yg lain gan, yg gratisan bisa sih tapi agak susahnya nyarinya
Kalo mau lancar pake proxy berbayar, kalo bisa proxy yg region china

**Comment by PixieID** [comment]
> > Uploadnya selalu gagal sampe udh nyoba 17x an. Klo gamake options , QQ ngeblock IP/Region
> 
> Pake proxy yg lain gan, yg gratisan bisa sih tapi agak susahnya nyarinya Kalo mau lancar pake proxy berbayar, kalo bisa proxy yg region china

Terima kasih lord.
